name: Deployment
on:
    workflow_run:
        workflows:
            - Build
        types:
            - completed

jobs:
    deploy-app:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.K_SERVER }}
                  username: ${{ secrets.K_USER }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: ${{ secrets.DEPLOYMENT_SCRIPT }}
