name: Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build-server:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: [1.16.3]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Tidy
              run: go mod tidy
            - name: Build
              run: go build

            - name: Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: kshoplistSrv
                  path: ./kshoplistSrv
                  retention-days: 5

    build-docker:
        runs-on: ubuntu-latest
        needs: [build-server]
        if: github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v4

            - name: Set Envs
              id: environment
              run: echo "VERSION=v$(date +'%Y.%m.%d')" >> $GITHUB_ENV

            - name: Download server artifact
              uses: actions/download-artifact@v4
              with:
                  name: 'kshoplistSrv'
                  path: ./kshoplistSrv

            - name: Set up Docker Builder
              uses: docker/setup-buildx-action@v3

            - name: Log into GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Push to Github Container Registry
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository }}:latest
                      ghcr.io/${{ github.repository }}:${{ env.VERSION }}
