name: Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build-server:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: [1.16.3]
        steps:
            - uses: actions/checkout@v2
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Tidy
              run: go mod tidy
            - name: Build
              run: go build

            - name: Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: kshoplistSrv
                  path: ./kshoplistSrv
                  retention-days: 5

    build-docker:
        runs-on: ubuntu-latest
        needs: [build-server]
        # if: github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v2

            - name: Set up Docker Builder
              uses: docker/setup-buildx-action@v1

            - name: Log into GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Push to Github Container Registry
              uses: docker/build-push-action@v2
              with:
                  context: .
                  version: latest
                  file: Dockerfile
                  push: true
                  tags: ghcr.io/${{ github.repository }}:latest
